FROM denoland/deno:2.1.4 AS deno-bin

FROM node:22-slim
COPY --from=deno-bin /usr/bin/deno /usr/local/bin/deno

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY tsconfig.json ./
COPY src/ ./src/

EXPOSE 3737
CMD ["npx", "tsx", "watch", "src/server.ts"]
